apiVersion: v2
name: ingress-controller-aws
description: A Helm chart for Kubernetes Ingress Controller on AWS
type: application
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx
    alias: ingress-nginx-aws
    condition: ingress-nginx-aws.enabled

